### ISSUE TITLE
Unable to generate self-signed certificate for CIM server the openssl.cnf is missing

### ISSUE THREAD

**Issue by alexanderjacuna** [NetAppDocs/smis-provider#4]
Page: [Generate a self-signed certificate for the CIM server](https://docs.netapp.com/us-en/smis-provider/task-generate-a-self-signed-certificate-for-the-cim-server-windows.html)

Where is the default location of the "openssl.cnf" file? Generating a self-signed certificate with the provided command example doesn't include a path to a "openssl.cnf" file.

**Comment by alexanderjacuna** [comment]
openssl req -new -key cimom.key -out cimom.csr

Requires a "-config" option with a location specified.

**Comment by alexanderjacuna** [comment]
This issue stems from either the OPENSSL_CONF environmental variable not defined in the customer's environment 

OR

The openssl.cnf simply doesn't exist.

**Comment by alexanderjacuna** [comment]
Found on:

SMI-S Provider 5.2.6P2

**Comment by ntap-bmegan** [comment]
@netapp-barbe - Is this work complete? If not, can you provide an estimate?

**Comment by ntap-bmegan** [comment]
This issue will be closed on **mon 14 nov** due to lack of activity within the last 90 days. @alexanderjacuna - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

FYI @jenatnetapp, @netapp-ehoffman

**Comment by alexanderjacuna** [comment]
@ntap-bmegan there has been no progress made on this issue. Original issue is still there. Needs to be kept open until our documentation is updated to cover the openssl.cnf location.

**Comment by ntap-bmegan** [comment]
Thanks, @alexanderjacuna. I'll follow up with the writing team.

**Comment by alexanderjacuna** [comment]
Thanks @ntap-bmegan !

**Comment by netapp-aoife** [comment]
Hi Chanda, this is still in progress. Please leave the issue open. Thanks!

**Comment by netapp-aoife** [comment]
Hi, thanks again for bringing this to our attention. This has now been addressed in our documentation: https://docs.netapp.com/us-en/smis-provider/task-generate-a-self-signed-certificate-for-the-cim-server-windows.html
