### ISSUE TITLE
Documentation lacks a procedure for customers with an expired CIM certificate

### ISSUE THREAD

**Issue by alexanderjacuna** [NetAppDocs/smis-provider#5]
Page: [Generate a self-signed certificate for the CIM server](https://docs.netapp.com/us-en/smis-provider/task-generate-a-self-signed-certificate-for-the-cim-server-windows.html)

When customer's self-signed certificates expire there is no documentation pointing to the steps needing to resolve. We only have for generating a self-signed certificate.

**Comment by ntap-bmegan** [comment]
@netapp-barbe - Is this work complete? If not, can you provide an estimate?

**Comment by ntap-bmegan** [comment]
This issue will be closed on **mon 14 nov** due to lack of activity within the last 90 days. @alexanderjacuna - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

FYI @jenatnetapp, @netapp-ehoffman
