### ISSUE TITLE
Request to add direct link

### ISSUE THREAD

**Issue by kevinh-netapp** [NetAppDocs/smis-provider#7]
Page: [Download the NetApp SMI-S Provider software package](https://docs.netapp.com/us-en/smis-provider/task-download-smi-s-provider.html)

Is there are reason we don't just link directly to the SMI-S download section of the support site here?  Thanks!

**Comment by netapp-ehoffman** [comment]
Hi Kevin, thanks for your question, and your great engagement with the docs team on GitHub. We don't have a method for tracking possible changes to these links, so our most sustainable model for all products is to provide generic NSS links. 
Ed
